SELECT COUNT(*) FROM USERS;
SELECT COUNT(*) FROM PROJECTS;
SELECT COUNT(*) FROM PUBLICITY_LINKS;
SELECT COUNT(*) FROM SUPPORT_REQUESTS;
SELECT COUNT(*) FROM HELP_REQUESTS;
SELECT COUNT(*) FROM FOOD_REQUESTS;
SELECT COUNT(*) FROM MONEY_REQUESTS;
SELECT COUNT(*) FROM CONTRIBUTIONS;
SELECT COUNT(*) FROM COMMENTS;
SELECT COUNT(*) FROM LIKES;
SELECT COUNT(*) FROM UPDATES;
SELECT COUNT(*) FROM TEAM_MEMBERSHIPS;

SELECT email FROM USERS;
