sqlldr djw2146@ADB/dudedude control=loader.ctl log=data_load.log
sqlldr djw2146@ADB/dudedude control=loader1.ctl log=data_load.log
sqlldr djw2146@ADB/dudedude control=loader2.ctl log=data_load.log
sqlldr djw2146@ADB/dudedude control=loader3.ctl log=data_load.log
sqlldr djw2146@ADB/dudedude control=loader4.ctl log=data_load.log
sqlldr djw2146@ADB/dudedude control=loader5.ctl log=data_load.log
sqlldr djw2146@ADB/dudedude control=loader6.ctl log=data_load.log
sqlldr djw2146@ADB/dudedude control=loader7.ctl log=data_load.log
sqlldr djw2146@ADB/dudedude control=loader8.ctl log=data_load.log
sqlldr djw2146@ADB/dudedude control=loader9.ctl log=data_load.log
sqlldr djw2146@ADB/dudedude control=loader10.ctl log=data_load.log
sqlldr djw2146@ADB/dudedude control=loader11.ctl log=data_load.log